<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>WarriorsOfEverdawn.Core</AssemblyName>
    <RootNamespace>WarriorsOfEverdawn.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WarriorsOfEverdawn.Core.Tests" />
  </ItemGroup>

</Project>
